# Generated by Django 5.0.7 on 2025-03-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_rename_answer_exam_answer_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='courses.course'),
        ),
    ]
