# Generated by Django 5.0.7 on 2025-05-02 15:03

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
